#!/usr/bin/env python3
"""Generate the app's per-question explainer dataset.

Explainers are short, AI-generated study notes shown to the learner *after*
they answer a question (in addition to their own notes). They are authored by
hand as JSON, one file per exam section, under `explanations/`:

    explanations/section-1.json   { "A-001-001-001": "…explainer…", … }
    explanations/section-2.json
    …

This script merges those files, validates every id against the question bank,
and emits an ES module the web app imports (`docs/js/data/explanations.js`).
The generated file is committed; regenerate it whenever a section file changes
— never hand-edit the generated module.

Authoring happens section by section, so it is fine for only some sections to
exist: questions without an explainer simply don't show one in the app.

Usage:  python3 scripts/build_explanations.py
"""
from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "amat_adv_quest_delim.txt"
SRC_DIR = ROOT / "explanations"
OUT = ROOT / "docs" / "js" / "data" / "explanations.js"

DISCLAIMER = (
    "AI-generated explanation — it may be imperfect, so double-check anything "
    "important against your study materials."
)


def valid_ids() -> set[str]:
    """The set of question ids defined in the source bank."""
    text = SOURCE.read_text(encoding="utf-8")
    ids = set()
    for raw in text.splitlines()[1:]:  # skip header row
        if not raw.strip():
            continue
        ids.add(raw.split(";", 1)[0].strip())
    if not ids:
        sys.exit(f"error: no question ids found in {SOURCE}")
    return ids


def section_of(qid: str) -> int:
    return int(qid.split("-")[1])


def load() -> dict[str, str]:
    if not SRC_DIR.is_dir():
        sys.exit(f"error: source directory {SRC_DIR} not found")

    ids = valid_ids()
    merged: dict[str, str] = {}
    files = sorted(SRC_DIR.glob("section-*.json"))
    if not files:
        sys.exit(f"error: no section-*.json files in {SRC_DIR}")

    for path in files:
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as e:
            sys.exit(f"error: {path.name} is not valid JSON: {e}")
        if not isinstance(data, dict):
            sys.exit(f"error: {path.name} must be a JSON object")
        for qid, text in data.items():
            if qid not in ids:
                sys.exit(f"error: {path.name} references unknown question id {qid!r}")
            if not isinstance(text, str) or not text.strip():
                sys.exit(f"error: {path.name} has an empty explainer for {qid}")
            if qid in merged:
                sys.exit(f"error: duplicate explainer for {qid} (in {path.name})")
            merged[qid] = text.strip()
    return merged


def main() -> None:
    explanations = load()
    ordered = dict(sorted(explanations.items()))
    by_section = Counter(section_of(qid) for qid in ordered)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(ordered, ensure_ascii=False, indent=0)
    disclaimer = json.dumps(DISCLAIMER, ensure_ascii=False)
    header = (
        "// AUTO-GENERATED by scripts/build_explanations.py — do not edit by hand.\n"
        "// Source: explanations/section-*.json (hand-authored; content is AI-generated).\n"
        "// Per-question study explainers shown after answering. Regenerate after edits.\n"
    )
    body = (
        f"{header}"
        f"export const EXPLANATIONS_DISCLAIMER = {disclaimer};\n"
        f"export const EXPLANATIONS = {payload};\n"
    )
    OUT.write_text(body, encoding="utf-8")

    print(f"wrote {len(ordered)} explainers -> {OUT.relative_to(ROOT)}")
    for section in sorted(by_section):
        print(f"  section {section} (A-{section:03d}): {by_section[section]} explainers")


if __name__ == "__main__":
    main()
