#!/usr/bin/env python3
"""Generate the app's question dataset from the source question bank.

Reads the semicolon-delimited Canadian Advanced amateur-radio question bank
(`amat_adv_quest_delim.txt`) and writes an ES module the web app imports.

Source format notes (see readme_adv.txt / CLAUDE.md):
  - UTF-8 with CRLF line endings.
  - Header row; first field name has a trailing space.
  - 11 fields per row, semicolon-delimited, no quoting (no field contains ';').
  - The correct answer is always field 3 (English) / field 8 (French); the
    app shuffles options at runtime so position carries no information.

The app is English-only, so only the English fields are emitted.

Usage:  python3 scripts/build_questions.py
"""
from __future__ import annotations

import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "amat_adv_quest_delim.txt"
OUT = ROOT / "docs" / "js" / "data" / "questions.js"

# Field indices in the source (0-based).
F_ID = 0
F_Q_EN = 1
F_CORRECT_EN = 2
F_WRONG_EN = (3, 4, 5)
EXPECTED_FIELDS = 11


def parse() -> list[dict]:
    text = SOURCE.read_text(encoding="utf-8")
    lines = text.splitlines()  # handles CRLF and the trailing newline
    if not lines:
        sys.exit(f"error: {SOURCE} is empty")

    questions: list[dict] = []
    for lineno, raw in enumerate(lines[1:], start=2):  # skip header row
        if not raw.strip():
            continue
        fields = [f.strip() for f in raw.split(";")]
        if len(fields) != EXPECTED_FIELDS:
            sys.exit(
                f"error: line {lineno} has {len(fields)} fields, "
                f"expected {EXPECTED_FIELDS}: {raw[:80]!r}"
            )
        qid = fields[F_ID]
        parts = qid.split("-")
        if len(parts) != 4 or parts[0] != "A":
            sys.exit(f"error: line {lineno} has unexpected id {qid!r}")
        questions.append(
            {
                "id": qid,
                "section": int(parts[1]),
                "sub": int(parts[2]),
                "num": int(parts[3]),
                "q": fields[F_Q_EN],
                "correct": fields[F_CORRECT_EN],
                "wrong": [fields[i] for i in F_WRONG_EN],
            }
        )
    return questions


def main() -> None:
    questions = parse()
    if not questions:
        sys.exit("error: no questions parsed")

    by_section = Counter(q["section"] for q in questions)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(questions, ensure_ascii=False, separators=(",", ":"))
    header = (
        "// AUTO-GENERATED by scripts/build_questions.py — do not edit by hand.\n"
        "// Source of truth: amat_adv_quest_delim.txt (regenerate after editing it).\n"
    )
    OUT.write_text(f"{header}export const QUESTIONS = {payload};\n", encoding="utf-8")

    print(f"wrote {len(questions)} questions -> {OUT.relative_to(ROOT)}")
    for section in sorted(by_section):
        print(f"  section {section} (A-{section:03d}): {by_section[section]} questions")


if __name__ == "__main__":
    main()
